version: '3'

networks:
  backend:
    external: true

services:
  es:
    build:
      context: ./clickhouse
      args:
        - CLICKHOUSE_VERSION=${CLICKHOUSE_VERSION}
    container_name: ch_clickhouse
    ports:
      - "${CLICKHOUSE_PORT}:9000"
    volumes:
      - ${DATA_PATH}/clickhouse:/var/lib/clickhosue
      - ./clickhouse/etc:/etc/clickhouse-server
    networks:
      - backend
